// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type APIErrorResponsePayload = { error: string, message: string, };

export type ActivateLicenseRequestPayload = { licenseKey: string, appVersion: string, appPlatform: string, };

export type ActivateLicenseResponsePayload = { activationId: string, };

export type CheckActivationResponsePayload = { active: boolean, };

export type LicenseCheckStatus = { "type": "personal_use" } | { "type": "commercial_use" } | { "type": "trialing", end: string, } | { "type": "trial_ended", end: string, };
