// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Template = 1,
  Tag = 4,
  Function = 5,
  Identifier = 6,
  ChainedIdentifier = 7,
  FunctionParamList = 10,
  Assignment = 11,
  String = 13,
  Boolean = 14,
  Number = 15,
  PlainText = 17
